backend:
  type: json

currency:
  name:
    singular: dollar
    plural: dollars
  balance-format: '{1} {2}'
  format: '0.00'
  grouping: 3
  grouping-separator: ','

chat:
  prefix: '&b[&9Economy&b]&r '

economy:
  start-balance: 0.0
  notify-start-balance: true
  server-account: '$SERVER$'
  baltop-update-interval: 300

multi-server-sync: false
update-check: true
locale-override: false
debug: false
