backend:
  type: flatfile

currency:
  name:
    singular: dollar
    plural: dollars
  format: '0.00'
  grouping: 3
  grouping-separator: ','

chat:
  prefix: '&b[&9Economy&b]&r '

economy:
  start-balance: 0.0
  notify-start-balance: true

debug: false
